import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { AppSidebar } from "~/components/ui/app-sidebar";
import { Breadcrumb } from "~/components/ui/breadcrumb";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (

    <html lang="en" className={`${GeistSans.variable}`}>

      <body>
        {/* <div className="breadcrumb-container"> 
          <Breadcrumb />
        </div> */}
        <div className="flex h-screen"> {/* Flex container for full-screen height */}
          <SidebarProvider>
            <AppSidebar /> {/* Example width for sidebar */}
            <main className="flex-1 p-4"> {/* Main content takes remaining space */}
              <SidebarTrigger />
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </main>
          </SidebarProvider>
        </div>
      </body>

    </html>


  );
}
